### ISSUE TITLE
Unable to run this project after download. Can you detail the process of running this project after download

### ISSUE THREAD

**Issue by sagarsingari** [yetanalytics/datasim-ui#5]
We're encountering a few errors when we try to run the project right after download. Could you please detail the process of running the project after download.

[clojure errors.txt](https://github.com/yetanalytics/datasim-ui/files/4593590/clojure.errors.txt)
[cljs core asyc.txt](https://github.com/yetanalytics/datasim-ui/files/4593592/cljs.core.asyc.txt)
[clinet-https.txt](https://github.com/yetanalytics/datasim-ui/files/4593593/clinet-https.txt)

Have attached a list of errors we get when we try to run it.

P.S:  We have added a few dependencies to try & fix the errors. The attached files contain the errors we have not been able to fix.

**Comment by cliffcaseyyet** [comment]
Hi,

Sorry to hear it was not seamless. Could you provide your JDK version, Clojure version, and Node version, as well as OS details?

I will try to reproduce on this end.

Thanks,
Cliff Casey

**Comment by sagarsingari** [comment]
Hi Cliff,

Have attached the details
![Config](https://user-images.githubusercontent.com/64849925/81342125-50b72a80-90d0-11ea-915a-9a260388933e.PNG)

Thanks fro your response!

**Comment by sagarsingari** [comment]
Clojure version
clojure-tools-1.10.1.536

**Comment by sagarsingari** [comment]
OS is Windows 10 64-bit

**Comment by cliffcaseyyet** [comment]
Hi,

I think I got my system specs in line with yours:
![system-setup](https://user-images.githubusercontent.com/54323005/81352223-057f2680-9094-11ea-8670-2e5cabaff95d.png)

Unfortunately I am not seeing the issue locally, however I did notice in your commands that you are attempting to run from java itself. What is your output when you run the clj command in the README:

`clojure -A:fig`

Thanks,
Cliff

**Comment by sagarsingari** [comment]
I get an error:
'clojure' is not recognised as an internal or external command, operable program or batch file

Hence I'm running from Java.

**Comment by sagarsingari** [comment]
Hey Cliff,
I got the problem resolved!
I changed my Java version to 11 and re-installed Clojure.
Probably it was the Clojure set up that was causing the error.

Thanks for your help!

**Comment by cliffcaseyyet** [comment]
Great, I'm glad you got it working. Let me know if you have any other questions.

Thanks,
Cliff

**Comment by sagarsingari** [comment]
Absolutely, we're trying to implement this and I think we'll get a few questions.

Thanks for your assistance & time !
